### ISSUE TITLE
Crash on iOS in version 1.0.0-rc0

### ISSUE THREAD

**Issue by YukiOya** [AgoraIO/Agora-Flutter-RTM-SDK#77] opened 2021-04-30 07:22 UTC
I crashed when I tried to log in without specifying token on iOS.

In Flutter's code, token seems to be optional.

https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/blob/master/lib/src/agora_rtm_client.dart#L225

However, the iOS code has been modified to require a token.

https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/commit/9bc138b335ff7dcaef5817a271f610e6bdcdd026#diff-720159b87f7299e84104e03713571d5799a066fd14ac0f7a5393b2ab43c97ac3L89-R90

Will I be unable to log in without a token in the future?

**Comment by plutoless** [comment] 2021-05-04 12:23
@YukiOya try using empty string in this case.

**Comment by YukiOya** [comment] 2021-05-06 06:31
@plutoless 
Thank you for your answer!

I tried it with an empty string, but it still crashed with the same error.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString stringValue]: unrecognized selector sent to instance 0x1df6c1fe8'
terminating with uncaught exception of type NSException
```

**Comment by LichKing-2234** [comment] 2021-05-07 03:22
pls show your code to help us find the cause.

**Comment by YukiOya** [comment] 2021-05-10 03:14
```dart
// Hide it because it's a sensitive value.
final appId = '';
final userId = '';

final client = await AgoraRtmClient.createInstance(appId);
await client.login('', userId);
```

**Comment by momoleu** [comment] 2021-05-13 19:25
Hello did someone resolve these issues? The solution given doesn't work @YukiOya @plutoless .

**Comment by JayPerfetto** [comment] 2021-05-13 21:38
also facing the same issue, with roughly the same code structure:
`   
    setClient(await AgoraRtmClient.createInstance(_AGORA_KEY));
    client.onConnectionStateChanged = (int state, int reason) {
      if (state == 5) {
        client.logout();
        print('Logout.');
        setIsLogin(false);
      }
    };
    await client.login('', userId);
`

**Comment by JayPerfetto** [comment] 2021-05-13 21:51
I got this working by rolling back to version 0.9.14 and wrapping my userId in quotes like this to explicitly pass it as a string (it is a UUID)

`await client.login('', '$userId');`

**Comment by LichKing-2234** [comment] 2021-05-14 02:30
this issue will be fixed net version as soon as possible.

**Comment by momoleu** [comment] 2021-05-15 12:25
Thank you all. I will wait for the next version so. Hope it will be soon.

**Closed** 2021-05-17 11:57 UTC
